calories_calculator/calories_calculator/apps/articles/urls.py
from django.urls import path

from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    # path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment'),
]

calories_calculator/calories_calculator/apps/user/urls.py
from django.urls import path 
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    
]

calories_calculator/calories_calculator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('accounts/', include('allauth.urls')),
]

calories_calculator/calories_calculator/apps/articles/models.py
import datetime
from django.db import models

from django.utils import timezone


class Article(models.Model):
    article_title = models.CharField('name_article', max_length=200)
    article_text = models.TextField('text_article')
    pub_date = models.DateTimeField('Data_published')

    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=7))


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('name_author', max_length=50)
    comment_text = models.CharField('text_comment', max_length=200)

    def __str__(self):
        return self.author_name

calories_calculator/calories_calculator/apps/user/models.py
from django.db import models

# Create your models here.

calories_calculator/calories_calculator/apps/articles/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from .models import Article, Comment


def index(request):
    latest_articles_list = Article.objects.order_by('-pub_date')[:5]
    return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list})


def detail(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Статья не найдена!")
    return render(request, 'articles/detail.html', {'article': a})

calories_calculator/calories_calculator/apps/user/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "user/index.html")

calories_calculator/calories_calculator/apps/user/templates/user/index.html
{% load socialaccount %}
{% providers_media_js %}
<!DOCTYPE html>

<head>
    <title>Social Login</title>

</head>

<body>
{{user}}
    <button><a href="{% provider_login_url "google" %}">Google Login</a></button>
    <button><a href="{% provider_login_url "facebook" method="js_sdk" %}">Facebook Login</a></button>
</body>

</html>

calories_calculator/calories_calculator/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}{{article.article_title}}{% endblock %}

{% block content %}

<h2>{{article.article_title}}</h2>
<p>{{article.article_text}}</p>
<em>{{article.pub_date}}</em>

<hr>


<hr>

<form action="{% url 'articles:leave_comment' article.id %}" method="POST"></form>

{% endblock %}

calories_calculator/calories_calculator/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}Последние статьи{% endblock %}

{% block content %}

           {% if latest_articles_list %}
{% for a in latest_articles_list %}
<a href="{% url 'articles:detail' a.id">{{a.article_title}}</a>
{% endfor %}
{% else %}
Статьи не найдены =(
{% endif %}

{% endblock %}

calories_calculator/calories_calculator/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}МОЙ САЙТ{% endblock %}</title>
</head>
<body>

{% block content %} {% endblock %}

</body>
</html>